import type { Material } from "@/types/material";

export const MATERIALS: Material[] = [
  {
    name: "Nylon 12 Powder", density: 1.01,
    profile: "Standard SLS workhorse — excellent balance of strength and rigidity",
    props: {
      "Ultimate Tensile Strength (MPa)":        "50",
      "Tensile Modulus (MPa)":                  "1850",
      "Elongation at Break (%)":                "11",
      "Shore Hardness":                         "74 D",
      "Printed Density (g/cc)":                 "0.99",
      "Notched Izod Impact Strength (J/m)":     "32.0",
      "Heat Deflection Temp @ 1.8 MPa (°C)":   "87",
      "Heat Deflection Temp @ 0.45 MPa (°C)":  "171",
      "Thermal Conductivity (W/m·K)":           "0.428",
      "Coeff. of Thermal Expansion (µm/m/°C)": "165",
      "Flammability (UL 94)":                   "HB @ 3mm",
      "Dielectric Strength (kV/mm)":            "8.82",
    },
  },
  {
    name: "Nylon 12 Tough Powder", density: 1.01, archived: true,
    profile: "High-impact variant — superior toughness for snap-fits and living hinges",
    props: {
      "Ultimate Tensile Strength (MPa)":       "42",
      "Tensile Modulus (MPa)":                 "1450",
      "Elongation at Break (%)":               "25",
      "Shore Hardness":                        "73 D",
      "Printed Density (g/cc)":                "1.01",
      "Notched Izod Impact Strength (J/m)":    "60.0",
      "Heat Deflection Temp @ 1.8 MPa (°C)":  "46",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "161",
      "Flammability (UL 94)":                  "HB @ 3mm",
      "Dielectric Strength (kV/mm)":           "2.05",
    },
  },
  {
    name: "Nylon 12 White Powder", density: 1.01, archived: true,
    profile: "Aesthetic SLS — clean white finish for consumer-facing or cosmetic parts",
    props: {
      "Ultimate Tensile Strength (MPa)":       "47",
      "Tensile Modulus (MPa)":                 "1950",
      "Elongation at Break (%)":               "8",
      "Notched Izod Impact Strength (J/m)":    "28.0",
      "Heat Deflection Temp @ 1.8 MPa (°C)":  "87",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "177",
      "Flammability (UL 94)":                  "HB @ 3mm",
    },
  },
  {
    name: "Nylon 12 GF Powder", density: 1.33, archived: true,
    profile: "Glass-filled SLS — improved stiffness and dimensional stability at elevated temps",
    props: {
      "Ultimate Tensile Strength (MPa)":        "38",
      "Tensile Modulus (MPa)":                  "2800",
      "Elongation at Break (%)":                "4",
      "Shore Hardness":                         "73 D",
      "Printed Density (g/cc)":                 "1.33",
      "Notched Izod Impact Strength (J/m)":     "36.0",
      "Heat Deflection Temp @ 1.8 MPa (°C)":   "113",
      "Heat Deflection Temp @ 0.45 MPa (°C)":  "170",
      "Thermal Conductivity (W/m·K)":           "0.532",
      "Coeff. of Thermal Expansion (µm/m/°C)": "125.8",
      "Flammability (UL 94)":                   "HB @ 3mm",
      "Dielectric Strength (kV/mm)":            "8.54",
    },
  },
  {
    name: "Nylon 11 Powder", density: 1.02, archived: true,
    profile: "Flexible SLS — highest elongation and impact for functional prototypes and wearables",
    props: {
      "Ultimate Tensile Strength (MPa)":       "49",
      "Tensile Modulus (MPa)":                 "1600",
      "Elongation at Break (%)":               "40",
      "Notched Izod Impact Strength (J/m)":    "71.0",
      "Heat Deflection Temp @ 1.8 MPa (°C)":  "46",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "182",
    },
  },
  {
    name: "Nylon 11 CF Powder", density: 1.10, archived: true,
    profile: "Carbon fiber reinforced — maximum stiffness for lightweight structural parts",
    props: {
      "Ultimate Tensile Strength (MPa)":        "69",
      "Tensile Modulus (MPa)":                  "5300",
      "Elongation at Break (%)":                "9",
      "Notched Izod Impact Strength (J/m)":     "74.0",
      "Heat Deflection Temp @ 1.8 MPa (°C)":   "178",
      "Heat Deflection Temp @ 0.45 MPa (°C)":  "188",
      "Coeff. of Thermal Expansion (µm/m/°C)": "47.2",
    },
  },
  {
    name: "TPU 90A Powder", density: 1.20, archived: true,
    profile: "Flexible elastomer — shock absorption, seals, grips, and flexible end-use parts",
    props: {
      "Ultimate Tensile Strength (MPa)":        "8.7",
      "Elongation at Break (%)":                "310",
      "Shore Hardness":                         "90 A",
      "Coeff. of Thermal Expansion (µm/m/°C)": "235",
      "Compression Set 23°C (22h)":             "0.205",
      "Compression Set 70°C (22h)":             "0.599",
    },
  },
  // ── Formlabs Resin Materials (ARCHIVED — SLA/LFS only, not SLS-compatible) ──
  {
    name: "Standard Resin (Clear)", density: 1.17, archived: true,
    profile: "General-purpose SLA resin — great for concept models and visualization",
    props: {
      "Ultimate Tensile Strength (MPa)":       "65",
      "Tensile Modulus (MPa)":                 "2800",
      "Elongation at Break (%)":               "6",
      "Notched Izod Impact Strength (J/m)":    "25",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "58",
      "Printed Density (g/cc)":                "1.17",
      "Shore Hardness":                        "83 D",
    },
  },
  {
    name: "Standard Resin (Grey)", density: 1.17, archived: true,
    profile: "Smooth grey finish resin — ideal for models, tooling and concept prototypes",
    props: {
      "Ultimate Tensile Strength (MPa)":       "65",
      "Tensile Modulus (MPa)":                 "2800",
      "Elongation at Break (%)":               "6",
      "Notched Izod Impact Strength (J/m)":    "25",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "58",
      "Printed Density (g/cc)":                "1.17",
      "Shore Hardness":                        "83 D",
    },
  },
  {
    name: "Standard Resin (White)", density: 1.17, archived: true,
    profile: "Clean white finish for consumer-facing prototypes and presentation models",
    props: {
      "Ultimate Tensile Strength (MPa)":       "65",
      "Tensile Modulus (MPa)":                 "2800",
      "Elongation at Break (%)":               "6",
      "Notched Izod Impact Strength (J/m)":    "25",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "58",
      "Printed Density (g/cc)":                "1.17",
      "Shore Hardness":                        "83 D",
    },
  },
  {
    name: "Standard Resin (Black)", density: 1.17, archived: true,
    profile: "Matte black finish for end-use-look prototypes and functional models",
    props: {
      "Ultimate Tensile Strength (MPa)":       "65",
      "Tensile Modulus (MPa)":                 "2800",
      "Elongation at Break (%)":               "6",
      "Notched Izod Impact Strength (J/m)":    "25",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "58",
      "Printed Density (g/cc)":                "1.17",
      "Shore Hardness":                        "83 D",
    },
  },
  {
    name: "Tough 1500 Resin", density: 1.22, archived: true,
    profile: "Tough & flexible SLA resin — ABS-like, good for snap-fits and living hinges",
    props: {
      "Ultimate Tensile Strength (MPa)":       "32",
      "Tensile Modulus (MPa)":                 "1500",
      "Elongation at Break (%)":               "53",
      "Notched Izod Impact Strength (J/m)":    "66",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "42",
      "Printed Density (g/cc)":                "1.22",
      "Shore Hardness":                        "74 D",
    },
  },
  {
    name: "Tough 2000 Resin", density: 1.22, archived: true,
    profile: "High strength & stiffness — best balance of toughness and modulus in SLA",
    props: {
      "Ultimate Tensile Strength (MPa)":       "46",
      "Tensile Modulus (MPa)":                 "2000",
      "Elongation at Break (%)":               "32",
      "Notched Izod Impact Strength (J/m)":    "57",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "52",
      "Printed Density (g/cc)":                "1.22",
      "Shore Hardness":                        "80 D",
    },
  },
  {
    name: "Durable Resin", density: 1.19, archived: true,
    profile: "PP-like SLA resin — wax-smooth surface, low friction, fatigue resistance",
    props: {
      "Ultimate Tensile Strength (MPa)":       "28",
      "Tensile Modulus (MPa)":                 "910",
      "Elongation at Break (%)":               "55",
      "Notched Izod Impact Strength (J/m)":    "60",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "42",
      "Printed Density (g/cc)":                "1.19",
      "Shore Hardness":                        "76 D",
    },
  },
  {
    name: "Rigid 4000 Resin", density: 1.57, archived: true,
    profile: "Glass-filled SLA — stiff, dimensionally stable for jigs, fixtures and housings",
    props: {
      "Ultimate Tensile Strength (MPa)":       "68",
      "Tensile Modulus (MPa)":                 "4000",
      "Elongation at Break (%)":               "3",
      "Notched Izod Impact Strength (J/m)":    "27",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "73",
      "Printed Density (g/cc)":                "1.57",
      "Shore Hardness":                        "87 D",
    },
  },
  {
    name: "Rigid 10K Resin", density: 1.78, archived: true,
    profile: "Highest-stiffness Formlabs resin — mineral-filled for molds, turbines, manifolds",
    props: {
      "Ultimate Tensile Strength (MPa)":       "65",
      "Tensile Modulus (MPa)":                 "10000",
      "Elongation at Break (%)":               "1",
      "Notched Izod Impact Strength (J/m)":    "24",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "218",
      "Heat Deflection Temp @ 1.8 MPa (°C)":  "160",
      "Printed Density (g/cc)":                "1.78",
      "Shore Hardness":                        "88 D",
    },
  },
  {
    name: "High Temp Resin", density: 1.22, archived: true,
    profile: "Highest HDT Formlabs resin (238°C @ 0.45 MPa) — testing jigs, hot air ducts",
    props: {
      "Ultimate Tensile Strength (MPa)":       "37",
      "Tensile Modulus (MPa)":                 "2800",
      "Elongation at Break (%)":               "1.4",
      "Notched Izod Impact Strength (J/m)":    "15",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "238",
      "Heat Deflection Temp @ 1.8 MPa (°C)":  "289",
      "Printed Density (g/cc)":                "1.22",
    },
  },
  {
    name: "Elastic 50A Resin", density: 1.10, archived: true,
    profile: "Ultra-soft SLA elastomer (50A) — cushioning, gaskets, ergonomic grips",
    props: {
      "Tensile Strength (MPa)":               "3.2",
      "Elongation at Break (%)":              "160",
      "Shore Hardness":                       "50 A",
      "Tear Strength (kN/m)":                 "9",
      "Compression Set (%)":                  "7.8",
      "Printed Density (g/cc)":               "1.10",
    },
  },
  {
    name: "Flexible 80A Resin", density: 1.15, archived: true,
    profile: "Soft flexible SLA resin — wearables, cushioning, soft-touch overmolds",
    props: {
      "Tensile Strength (MPa)":               "7.7",
      "Elongation at Break (%)":              "110",
      "Shore Hardness":                       "80 A",
      "Tear Strength (kN/m)":                 "23",
      "Printed Density (g/cc)":               "1.15",
    },
  },
  {
    name: "Grey Pro Resin", density: 1.19, archived: true,
    profile: "Fine-feature accuracy resin — tight tolerances, detailed anatomical models",
    props: {
      "Ultimate Tensile Strength (MPa)":       "66",
      "Tensile Modulus (MPa)":                 "3000",
      "Elongation at Break (%)":               "7",
      "Notched Izod Impact Strength (J/m)":    "33",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "60",
      "Printed Density (g/cc)":                "1.19",
      "Shore Hardness":                        "84 D",
    },
  },
  {
    name: "Engineering V4 Resin", density: 1.17, archived: true,
    profile: "Versatile engineering resin — good impact resistance for functional parts",
    props: {
      "Ultimate Tensile Strength (MPa)":       "68",
      "Tensile Modulus (MPa)":                 "2600",
      "Elongation at Break (%)":               "8",
      "Notched Izod Impact Strength (J/m)":    "32",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "56",
      "Printed Density (g/cc)":                "1.17",
    },
  },
  {
    name: "BioMed Clear Resin", density: 1.18, archived: true,
    profile: "ISO 10993 biocompatible — medical devices, surgical planning, dental guides",
    props: {
      "Ultimate Tensile Strength (MPa)":       "50",
      "Tensile Modulus (MPa)":                 "2700",
      "Elongation at Break (%)":               "5",
      "Notched Izod Impact Strength (J/m)":    "25",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "52",
      "Printed Density (g/cc)":                "1.18",
      "Biocompatibility":                      "ISO 10993",
    },
  },
  {
    name: "BioMed Amber Resin", density: 1.20, archived: true,
    profile: "Sterilisable biocompatible resin — autoclavable for surgical tools and guides",
    props: {
      "Ultimate Tensile Strength (MPa)":       "57",
      "Tensile Modulus (MPa)":                 "2700",
      "Elongation at Break (%)":               "5",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "60",
      "Printed Density (g/cc)":                "1.20",
      "Biocompatibility":                      "ISO 10993, autoclavable",
    },
  },
  {
    name: "Castable Wax Resin", density: 1.13, archived: true,
    profile: "100% wax-content resin — clean burnout for direct investment casting",
    props: {
      "Ash Content (%)":                       "<0.01",
      "Burnout Temperature (°C)":              "1370",
      "Printed Density (g/cc)":                "1.13",
      "Shore Hardness":                        "25 D",
    },
  },
  {
    name: "Castable Wax 40 Resin", density: 1.09, archived: true,
    profile: "40% wax-filled — stronger patterns with clean burnout for jewelry casting",
    props: {
      "Ash Content (%)":                       "<0.01",
      "Elongation at Break (%)":               "1.5",
      "Flexural Strength (MPa)":               "26",
      "Printed Density (g/cc)":                "1.09",
    },
  },
  {
    name: "Dental Model Resin", density: 1.21, archived: true,
    profile: "High-accuracy dental model resin — precise crown and bridge study models",
    props: {
      "Ultimate Tensile Strength (MPa)":       "60",
      "Tensile Modulus (MPa)":                 "3200",
      "Elongation at Break (%)":               "3",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "60",
      "Printed Density (g/cc)":                "1.21",
    },
  },
  {
    name: "Dental SG Resin", density: 1.19, archived: true,
    profile: "Surgical guide resin — ISO Class I biocompatible, autoclavable",
    props: {
      "Ultimate Tensile Strength (MPa)":       "55",
      "Tensile Modulus (MPa)":                 "3100",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "56",
      "Printed Density (g/cc)":                "1.19",
      "Biocompatibility":                      "ISO 10993 Class I, autoclavable",
    },
  },
  {
    name: "Color Kit Resin", density: 1.17, archived: true,
    profile: "Pigmented standard resin — same mechanical properties in cyan, magenta, yellow",
    props: {
      "Ultimate Tensile Strength (MPa)":       "65",
      "Tensile Modulus (MPa)":                 "2800",
      "Elongation at Break (%)":               "6",
      "Heat Deflection Temp @ 0.45 MPa (°C)": "58",
      "Printed Density (g/cc)":                "1.17",
    },
  },
  {
    name: "ESD Resin", density: 1.46, archived: true,
    profile: "Electrostatic dissipative — safe handling of electronics and PCBs in manufacturing",
    props: {
      "Ultimate Tensile Strength (MPa)":         "32",
      "Tensile Modulus (MPa)":                   "3800",
      "Elongation at Break (%)":                 "1.4",
      "Heat Deflection Temp @ 0.45 MPa (°C)":   "77",
      "Surface Resistivity (Ω/sq)":              "~1×10⁸",
      "Printed Density (g/cc)":                  "1.46",
    },
  },
  {
    name: "Silicone 40A Resin", density: 1.11, archived: true,
    profile: "True silicone SLA material — overmolds, seals, medical-grade parts",
    props: {
      "Tensile Strength (MPa)":                "2.8",
      "Elongation at Break (%)":               "160",
      "Shore Hardness":                        "40 A",
      "Tear Strength (kN/m)":                  "8",
      "Printed Density (g/cc)":                "1.11",
    },
  },
  {
    name: "Alumina 4N Resin", density: 3.04, archived: true,
    profile: "Technical ceramic (99.99% Al₂O₃) — extreme hardness, thermal and chemical resistance",
    props: {
      "Sintered Density (g/cc)":               "3.97",
      "Hardness (Vickers)":                    "~1700 HV",
      "Flexural Strength (MPa)":               "300–600",
      "Max Service Temperature (°C)":          "1600",
      "Dielectric Strength (kV/mm)":           "10–35",
      "Printed (green) Density (g/cc)":        "3.04",
    },
  },
];
